services:
  frps:
    build: 
      context: .
    image: hunglin59638/frp:${TAG}
    environment:
      - FRP_MODE=frpc
      - TOKEN=${TOKEN}
      - SERVER_ADDR=${SERVER_ADDR}
      - SERVER_PORT=${SERVER_FRP_PORT}
      - APP_LOCAL_IP=${APP_LOCAL_IP}
      - APP_LOCAL_PORT=${APP_LOCAL_PORT}
      - APP_SERVER_PORT=${APP_SERVER_PORT}

    restart: always

